# Generated by Django 4.0.4 on 2022-05-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('PhoneNo', models.IntegerField()),
            ],
        ),
    ]
