# Generated by Django 4.0.4 on 2022-05-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailSend', '0002_remove_details_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
