# Generated by Django 4.0.4 on 2022-05-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailSend', '0003_details_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
