# Generated by Django 4.0.4 on 2022-05-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailSend', '0004_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='Email',
        ),
        migrations.AddField(
            model_name='login',
            name='UserID',
            field=models.IntegerField(default=1),
        ),
    ]
